Repository loomnetwork/cryptozombie-lessons, pull requests merged in 2018-07, with the labels that each got.

#263 Fix wrongly capitalized variable names in Lesson 6 chapters 7-9
  en/6/07.md
  en/6/08.md
  en/6/09.md
  es/6/07.md
  es/6/08.md
  es/6/09.md
  fr/6/07.md
  fr/6/08.md
  fr/6/09.md
  jp/6/07.md
  jp/6/08.md
  jp/6/09.md
  ko/6/07.md
  ko/6/08.md
  ko/6/09.md
  pt/6/07-sending-transactions.md
  pt/6/08-calling-payable-functions.md
  pt/6/09-subscribing-to-events.md
Labels: conflict, help wanted

#300 Update 08.md
  en/6/08.md
Labels: conflict, help wanted

#289 fix-en-lesson6-chapter5
  en/6/05.md
  en/6/07.md
Labels: waiting terms

#301 Update 5-inheritance.md
  ko/2/5-inheritance.md
Labels: help wanted, waiting terms

#298 Update functions3.md
  ko/1/functions3.md
Labels: checking translation, help wanted, waiting terms

#295 Refine some jp translations in chapter 1 and 2
  jp/1/contracts.md
  jp/1/events.md
  jp/1/functions2.md
  jp/1/functions3.md
  jp/2/7-storage.md
Labels: checking translation, help wanted
