Repository loomnetwork/cryptozombie-lessons, pull requests merged in 2018-09, with the labels that each got.

#272 Fix some formatting and typos in zh-cn version
  zh/2/13-kittygenes.md
  zh/2/8-feedandmultiply2.md
  zh/3/01-externaldependencies.md
  zh/3/04-gas.md
  zh/3/05-timeunits.md
Labels: checking translation, help wanted

#292 fix error: chinese modulus sign
  zh/2/13-kittygenes.md
Labels: checking translation, help wanted

#293 Update 05-timeunits.md
  zh/3/05-timeunits.md
Labels: checking translation, help wanted

#322 Adding rewards button label
  en/index.json
  es/index.json
  fr/index.json
  jp/index.json
  ko/index.json
  pt/index.json
  ru/index.json
  th/index.json
Labels: bug, enhancement, help wanted

#308 Fixed Semicolon and Upper/Lower case. And matched to Document.
  jp/6/01.md
  jp/6/04.md
  jp/6/05.md
  jp/6/06.md
  jp/6/07.md
  jp/6/08.md
  jp/6/09.md
Labels: enhancement

#327 Fix a typo and errors in Korean
  ko/5/00-overview.md
  ko/6/06.md
Labels: checking translation, help wanted

#329 Fix a typo and errors in ko/3/04-gas.md and ko/6/05.md
  ko/3/04-gas.md
  ko/6/05.md
Labels: checking translation, help wanted

#332 Fix typo & duplicated text in ko 5, 6
  ko/5/05-erc721-5.md
  ko/6/08.md
Labels: checking translation, help wanted

#333 Update 2.md
  es/6/02.md
Labels: checking translation, help wanted

#336 Fix grammar in Lesson 6 Ch 1
  en/6/01.md
Labels: checking translation, help wanted

#337 Fix Korean typo in Lesson 3 Ch 10
  ko/3/10-savinggasview.md
Labels: checking translation, help wanted
